### ISSUE TITLE
Crete a theme for Leftwm

### ISSUE THREAD

**Issue by ghaerdi** [SAGAtheme/SAGA#1]
I'm creating a new theme for [Leftwm](https://github.com/leftwm/leftwm) using SAGA color palette, actually I recycled almost everything from [Miusaky/bspdots repo](https://github.com/Miusaky/bspdots) but I did a few changes.

Here is the link of the theme I'm talking about: https://github.com/ghaerdi/SAGA

I'm interested to submit all those config in a new SAGAtheme's repository.

**Comment by ghaerdi** [comment]
I almost forgot to say something. There is some work for the next days but for now it is usable.

**Comment by ghost** [comment]
@ghaerdi Didn't see this so I apologize for not responding very quickly. Thanks for the contribution. You can create a pull request [here](https://github.com/SAGAtheme/LeftWM/pulls).

**Comment by ghaerdi** [comment]
@Miusaky [Here is the pull request](https://github.com/SAGAtheme/LeftWM/pull/1). Waiting for your review.

**Comment by ghost** [comment]
Looks fine. Merged it. Since I don't use LeftWM I don't plan on maintaining this. Is that something you would like to do?

**Comment by ghaerdi** [comment]
@Miusaky Sure. I can use a little of my free time for this.

**Comment by ghost** [comment]
Added. Thanks!
